env = [
	["MASTER_TOKEN", "123"]
]

[server]
host = "127.0.0.1"
port = 5500

[api]
version = "0.1.0"
assets_path = "assets"
db_path = "sqlite:scraper_api.db"
db_max_conn = 2
handlers_count = 0
handler_queue_limit = 21

#[scraper]

[browser]
# Optional configuration:
# executable = ""
# user_data_dir = ""

# DEFAULT ARGS:
#    "--disable-blink-features=AutomationControlled",
#    "--disable-default-apps",
#    "--no-first-run",
#    "--disable-sync",
#    "--lang=en_US",
#    "--no-default-browser-check",
#    "--disable-smooth-scrolling",
#    "--disable-features=TranslateUI"
args = [
    "--disable-blink-features=AutomationControlled",
    "--disable-default-apps",
    "--no-first-run",
    "--disable-sync",
    "--lang=en_US",
    "--no-default-browser-check",
    "--disable-smooth-scrolling",
    "--disable-features=TranslateUI"
]
# 0: Falsse, 1: True, 2: New
headless_mod = 0
sandbox = false
extensions = []
incognito = false
# >= api.task_handlers
available_ports = [
	0,
]
launch_timeout = 1500
request_timeout = 2000
cache_enabled = true

[browser.timings]
launch_sleep = 280
set_proxy_sleep = 180
action_sleep = 80
wait_page_timeout = 700

[browser.page_param]
stealth_mode = false
rand_user_agent = false

[browser.page_param.duration]
base_ = 0
oz = 0
wb = 0
ym = 0
mm = 0
