env = [
    ["MASTER_TOKEN", "1234"]
]
pub_env = [
    ["PRINT_LOGS", "1"],
    ["VERSION", "v1.0.0"],
    ["LAST_UPDATE", "1/14/25"],
    ["GITHUB", "https://github.com/Nikita55612/RustScraperApi"],
    ["CONTACT", "https://t.me/Nikita5612"],
    ["LANG", "Rust"]
]

[server]
host = "127.0.0.1"
port = 5050

[api]
root_api_path = "/api/v1"
description_file_path = "assets/API_DESCRIPTION.md"
log_file_path = "api.log"
assets_path = "assets"
db_path = "sqlite:scraper_api.db"
db_max_conn = 2
handlers_count = 3
handler_queue_limit = 30
task_ws_sending_interval = 200
open_ws_limit = 100
interrupt_check_step = 60
available_markets = [
    "oz",
    "wb",
    "ym",
    "mm",
]
[api.test_token]
ttl = 86400
op_limit = 40
tc_limit = 1


[browser]
users_temp_data_dir = "./users_temp_data"
args = [
    "--disable-blink-features=AutomationControlled",
    "--disable-default-apps",
    "--no-first-run",
    "--disable-sync",
    "--lang=en_US",
    "--no-default-browser-check",
    "--disable-smooth-scrolling",
    "--disable-features=TranslateUI",
]
headless_mod = 0
sandbox = false
extensions = []
incognito = false
launch_timeout = 1500
request_timeout = 2000
cache_enabled = true

[browser.timings]
launch_sleep = 240
set_proxy_sleep = 160
action_sleep = 80
page_goto_timeout = 1200

[browser.page_param]
rand_user_agent = false
wait_for_element_timeout = 1100

[browser.page_param.symbol]
oz.wait_for_product_element = "body > pre"
ym.wait_for_product_element = """div[data-baobab-name="productSnippet"]"""
mm.wait_for_product_element = """meta[itemprop="price"]"""

[req_session]
set_proxy_interval = 16
close_tabs_interval = 40
launch_sleep = 180

[req_session.timings]
timeout = 700
conn_timeout = 500
read_timeout = 500
