[server]
host = "127.0.0.1"
port = 5500

[api]
version = "0.1.0"
assets_path = "assets"
db = "sqlite:scraper_api.db"
db_max_conn = 2
task_handlers = 0
handler_queue_limit = 21

[scraper]
