env = [
    ["MASTER_TOKEN", "1234"],
]
pub_env = [
    ["VERSION", "v1.0.0"],
    ["LAST_UPDATE", "1/14/25"],
    ["GITHUB", "-"],
    ["CONTACT", "https://t.me/Nikita5612"],
    ["LANG", "Rust"],
    ["WEB_DEP", "axum==0.7.9"],
]

[server]
host = "127.0.0.1"
port = 5050

[api]
assets_path = "assets"
db_path = "sqlite:scraper_api.db"
db_max_conn = 2
handlers_count = 1
handler_queue_limit = 10
task_ws_sending_interval = 1000
open_ws_limit = 20
interrupt_check_step = 60
available_markets = [
    "oz",
    "wb",
    "ym",
    "mm",
]
[api.test_token]
ttl = 86400
op_limit = 40
tc_limit = 1


[browser]
users_temp_data_dir = "./users_temp_data"
args = [
    "--disable-blink-features=AutomationControlled",
    "--disable-default-apps",
    "--no-first-run",
    "--disable-sync",
    "--lang=en_US",
    "--no-default-browser-check",
    "--disable-smooth-scrolling",
    "--disable-features=TranslateUI",
]
headless_mod = 0
sandbox = false
extensions = []
incognito = false
launch_timeout = 1500
request_timeout = 2000
cache_enabled = true

[browser.timings]
launch_sleep = 300
set_proxy_sleep = 180
action_sleep = 80
page_goto_timeout = 1400

[browser.page_param]
rand_user_agent = false
wait_for_element_timeout = 1000

[browser.page_param.symbol]
oz.wait_for_product_element = "body > pre"
ym.wait_for_product_element = """div[data-baobab-name="productSnippet"]"""
mm.wait_for_product_element = """meta[itemprop="price"]"""

[req_session]
set_proxy_interval = 14
close_tabs_interval = 40
launch_sleep = 200

[req_session.timings]
timeout = 700
conn_timeout = 500
read_timeout = 500
